### PR TITLE
[definitions-parser] skip scripts folder

### PR DESCRIPTION
**Pull request by KhooHaoYit**
Partially unblocks DefinitelyTyped/DefinitelyTyped#67259 and DefinitelyTyped/DefinitelyTyped#67291

When doing type checking on CI, the package that depends on it might use it in the `scripts` folder while not using it in the `types` folder, causing the CI to fail from missing dependencies due to `pnpm` only installs packages which got affected

In DefinitelyTyped/DefinitelyTyped#67259 case `pnpm` installed packages for
```
es-abstract/scripts
get-intrinsic/scripts
lodash-es/scripts
material-ui/scripts
...
```
While the CI checks typing for
```
es-abstract
get-intrinsic
lodash-es
material-ui
...
```
This PR fixes that issue by skipping type checking for `scripts` folder

### CODE REVIEW

**Comment by KhooHaoYit** [comment]
@microsoft-github-policy-service agree

**Comment by jakebailey** [comment]
FWIW I would really like to stop (generally) using path only information in the repo and instead determine paths are part of which package by looking for and reading package.json files (something I have done in #788. I don't really want to special case script does in specific directories when we know exactly which folders are packages based on their proximity to a package.json with the right name.

This might be okay as a hack, but it's not wrong for a package to contain a folder named "scripts" that's actually meant to be packaged.

**Comment by jakebailey** [comment]
(to be clear it may be okay for a hack in the short term, but I'm just noting my thought before I forget)

**Comment by jakebailey** [comment]
This PR will need a changeset to be accepted. I'd push to your PR to add one, but you've sent the PR from your master branch which is a little wonky, but I can still push.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
