### PR TITLE
Converted no-useless-files from TSLint to ESLint

### PR DESCRIPTION
**Pull request by AlexMunoz**
Following #514 I migrated the no-useless-files rule.

### CODE REVIEW

**Review by JoshuaKGoldberg — COMMENTED** [review]
I'm not a maintainer on this repo, but just looking from an outsider's perspective, the new rule and its tests look great! Nicely done! 🔥

**Comment by AlexMunoz** [comment]
Waiting until [Tooling: dt-header fast follow fixes](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61805) gets merged.

**Comment by sandersn** [comment]
per @JoshGoldberg's reminder, no-useless-files needs to be removed from dt.json

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
I removed it since I need to run the rule on all of Definitely Typed.

**Review by sandersn — CHANGES_REQUESTED** [review]
Fails on gapi.client.*, because the entire index.d.ts consists of:

```ts
// Type definitions for non-npm package Workflow Executions API v1 1.0
// Project: https://cloud.google.com/workflows
// Definitions by: Maxim Mazurok <https://github.com/Maxim-Mazurok>
//                 Nick Amoscato <https://github.com/namoscato>
//                 Declan Vong <https://github.com/declanvong>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.8

// Referenced type definitions are generated by https://github.com/Maxim-Mazurok/google-api-typings-generator
// In case of any problems please open issue in https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/new

/// <reference types="@maxim_mazurok/gapi.client.workflowexecutions" />
```

**Comment by AlexMunoz** [comment]
The rule now also looks for whether the file content has path/types references.

**Comment by sandersn** [comment]
Looks like a solid improvement but I need to test it on DT now.

**Comment by sandersn** [comment]
Finally got a clean-ish run:

My PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61925 is still missing 1 package:

Still has tslint-disable comment in file:
- source-map-support/register.d.ts

**Review by sandersn — APPROVED** [review]

**Pull request merged**
