### PR TITLE
feat: add `type-fest` to `allowedPackageJsonDependencies.txt`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Needed for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59806

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Ping @sandersn @andrewbranch

**Comment by MichaelDeBoey** [comment]
@andrewbranch @sandersn Is there anything I still need to do before I can get this one merged?

**Comment by andrewbranch** [comment]
Not merging here unless the usage is approved on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59806. I don’t think any DT package should use this.

**Comment by MichaelDeBoey** [comment]
I've included the necessary types inline in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59806.

**Pull request closed without merging**
