### PR TITLE
remove array-type eslint rule

### PR DESCRIPTION
**Pull request by iisaduan**
The `"array-type":"error"` behavior, seems to have changed in the most recent typescript-eslint release, and as a result, it is generating new [errors](https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/9777487309). 

With the addition of the default setting, the error message also becomes wrong:
image

### CODE REVIEW

**Comment by jakebailey** [comment]
Isn't this error right? Readonly of array is not ReadonlyArray and that's usually always a mistake...

**Comment by iisaduan** [comment]
>Isn't this error right? Readonly of array is not ReadonlyArray and that's usually always a mistake...

The error message changes when you remove the `default`, so at least one of the messages are wrong

image

**Comment by iisaduan** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/9498 well I filed a bug

**Review by jakebailey — COMMENTED** [review]
Removing it seems fine, but this PR needs a changeset.

**Review by sandersn — APPROVED** [review]

**Comment by jakebailey** [comment]
Updated the PR so we can get it in.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
