### PR TITLE
Switch all dt-tools references from master to main

### PR DESCRIPTION
**Pull request by jakebailey**
These are all of the bits and bobs here that need to change when we change the branch name.

### CODE REVIEW

**Review by sandersn — APPROVED** [review]
I guess we should hold this until after @JoshuaKGoldberg 's tslint removal PR is in, unless git's redirect ability is truly seamless.

**Comment by jakebailey** [comment]
It should be! But, happy to wait to make sure.

**Comment by sandersn** [comment]
I just haven't used it before; if you're satisfied with its ability to not disrupt open PRs, we might as well ship this.

**Comment by jakebailey** [comment]
This is what we'll have to do locally:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by jakebailey** [comment]
Okay, rename happened. Closing and reopening to make sure it works.

**Comment by jakebailey** [comment]
To fix everything locally, go to https://github.com/jakebailey/DefinitelyTyped-tools/settings and rename master to main (for your own fork, not mine).

Then locally run:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
get remote set-head origin -a
```

**Comment by JoshuaKGoldberg** [comment]
👍 confirmed - I can go through and update any PRs on my end.

**Comment by jakebailey** [comment]
No need, they're already updated. Mainly this is just to not have goofy branches on your fork.

**Pull request merged**
