### PR TITLE
feat: add @prisma/client to allowed package list

### PR DESCRIPTION
**Pull request by euxn23**

### CODE REVIEW

**Comment by andrewbranch** [comment]
This is no longer needed, right?

**Comment by euxn23** [comment]
No, this is needed.

**Comment by andrewbranch** [comment]
I thought https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51493 was meant to replace https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51469?

**Comment by euxn23** [comment]
After this p-r merged, I will add @prisma/client to type definition.

**Comment by andrewbranch** [comment]
I don’t think `@prisma/client` is ever safe to be a DT dependency, because it depends on user-generated files in node_modules: https://unpkg.com/browse/@prisma/client@2.18.0/index.d.ts

**Comment by euxn23** [comment]
Oh, I overlooked that. Now I also think this library is not safe to DefinitelyTyped, so I close this p-r. Thx.

**Pull request closed without merging**
