### PR TITLE
Remove applicationinsights

### PR DESCRIPTION
**Pull request by sandersn**
Based on an analysis of azure usage with @RyanCavanaugh.

This hasn't worked for a long time, because there's a bug in the publish notification code that runs before the call to application insights. I'm not sure whether to delete *that* or to fix it. Publication has been reliable (and predictable!--since the Functions changeover) for a long time so neither the notification nor the stats are as necessary as they once were.

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]

**Comment by sandersn** [comment]
Note to self: after I merge and ship this, I need to remove APPINSIGHTS_INSTRUMENTATIONKEY from Azure as well. (it silently fails to log without it, and we're already not logging successfully, so actually I guess it's OK to delete it whenever)

**Comment by andrewbranch** [comment]
This is how we see logs when the publisher crashes. This was definitely working and useful fairly recently.

**Comment by jakebailey** [comment]
Oh :(

**Comment by andrewbranch** [comment]
To clarify, I don’t think we were using the events, but I believe the setup/start calls are necessary in order to see stdout/stderr in the Azure portal.

**Comment by sandersn** [comment]
All right, I'll revert it tomorrow and then remove only the event logging.

**Pull request merged**
