### PR TITLE
Add googleapis to allowed dependencies

### PR DESCRIPTION
**Pull request by KonradPerlicki**
Required for: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65283

### CODE REVIEW

**Review by jakebailey — CHANGES_REQUESTED** [review]
Er, aren't all Google APIs already covered by the gapi packages?

**Comment by KonradPerlicki** [comment]
You're right, I have replaced the package, thanks and I'm closing PR

**Comment by jakebailey** [comment]
On second look, I don't know that the gapi packages are the right ones because of their global behavior, actually...

**Comment by jakebailey** [comment]
But maybe googleapis does that too. Not really sure what the difference is between them.

**Comment by KonradPerlicki** [comment]
The original package uses googleapis so It was my first thought to use it as well

**Comment by jakebailey** [comment]
Ah, then that settles that. 127MB package, though, wow!

**Comment by KonradPerlicki** [comment]
So, will you accept that and should I revert my last changes from [previous](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65283) or what now?

**Comment by jakebailey** [comment]
Yes, given the npm package depends on `googleapis`.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
