### PR TITLE
Add archiver to allowedPackageJsonDependencies.txt

### PR DESCRIPTION
**Pull request by janickvwcotiss**
- Add package "archiver" to allowedPackageJsonDependencies.txt
- Sort the file alphabetically using VSCodes "Sort Lines Ascending" command

### CODE REVIEW

**Comment by janickvwcotiss** [comment]
@microsoft-github-policy-service agree company="Cotiss"

**Comment by jakebailey** [comment]
Can you please provide context for why this dep is needed?

**Comment by janickvwcotiss** [comment]
> Can you please provide context for why this dep is needed?

Hi there Jake, thanks for taking a look at this PR. I have added this package in relation to my PR into the main DT repo, I am importing some types from the archiver package e.g.
```ts
import { Archiver, ArchiverOptions, EntryData, Format } from "archiver";
```

However, I think I may have open this PR prematurely as I didn't realise that Archiver itself doesn't have types and the types are actually being imported from `@types/archiver` see package.json:
```json
    "dependencies": {
        "@aws-sdk/client-s3": "^3.0.0",
        "@types/archiver": "^6.0.9999"
    }
```

Since I'm importing the types from another DT repo I believe that this addition to the allowedPackageJsonDependencies.txt isn't actually needed, but I could be wrong and would appreciate your guidance, it's my first time adding a DT package from scratch. 

If this PR isn't needed for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67887 then I (or you) can close this PR.

Thanks again.

**Comment by jakebailey** [comment]
Yes, if it's on DT, then you don't need to submit it here; your PR is passing tests.

**Comment by janickvwcotiss** [comment]
Thanks @jakebailey

**Pull request closed without merging**
