### PR TITLE
Added react-hooks-compose

### PR DESCRIPTION
**Pull request by paulcarroll**
Adding type definitions in DefinitelyTyped for [react-hooks-compose](https://github.com/helloitsjoe/react-hooks-compose)

### CODE REVIEW

**Comment by jakebailey** [comment]
Can you please link which DT PR this change is needed for?

**Comment by paulcarroll** [comment]
Sure thing @jakebailey  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69720

**Comment by jakebailey** [comment]
I don't see why this change is required, your PR introduces the types for this package to DT, so you necessarily don't need the upstream package.

**Comment by paulcarroll** [comment]
Fair enough, this is my first DT submission and I must've misunderstood

Basically the test fails with the following (which is what lead me to believe it was needed here):

```
❯ npx pnpm@v8.15.1 test-all                                                               base  3.0.0 09:00:58

> definitely-typed@0.0.3 test-all /Users/paulcarroll/Dev/community/DefinitelyTyped
> node --enable-source-maps node_modules/@definitelytyped/dtslint-runner/ --path .

dtslint-runner@0.1.23
Node version:  v20.12.2
Using local DefinitelyTyped at /Users/paulcarroll/Dev/community/DefinitelyTyped
Error: react-hooks-compose: In package.json: Dependency react-hooks-compose not in the allowed dependencies list.
Please make a pull request to microsoft/DefinitelyTyped-tools adding it to `packages/definitions-parser/allowedPackageJsonDependencies.txt`.
    at prepareAffectedPackages (/Users/paulcarroll/Dev/community/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint-runner@0.1.23_typescript@5.5.0-dev.20240531/node_modules/@definitelytyped/dtslint-runner/src/prepareAffectedPackages.ts:23:11)
```

My question is, how do I get the DT tests running if the logged warning is incorrect? Thanks in advance!

**Comment by jakebailey** [comment]
I left comments on your PR which will address that.

**Comment by paulcarroll** [comment]
Ahh, right, I understand.

Thanks for the help and patience!

**Pull request closed without merging**
