### PR TITLE
chore: remove ts3.6 support

### PR DESCRIPTION
**Pull request by SimonSchick**
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54895

Turns out this was harder than just 1 PR 😂

### CODE REVIEW

**Review by sandersn — CHANGES_REQUESTED** [review]
I love that you're getting rid of node's 3.6 types, but I want to hold this particular PR until TS4.4 actually releases. Now that we've been on the same release cadence for two years, it makes sense to add support for a new version and remove support for an old version at the same time.

Let's keep this PR around and you or I can push the 4.4 release changes to it, then merge+ship it at the actual 4.4 release.

**Comment by SimonSchick** [comment]
Yea np, would be nice if there was a script that does this automatically but I think it's simple enough.

**Comment by sandersn** [comment]
I added 4.5 -- a bit late, since it was supposed to be when the RC released -- so when tests finish I'll merge this. Then I'll remove 3.6 from the non-node packages on DT later today.

**Comment by SimonSchick** [comment]
🔥

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
OK, it's in. Give me a few minutes to update dtslint and dts-critic and then DT's tests should be good to remove ts3.6/ directories.

**Comment by sandersn** [comment]
OK, dtslint is up-to-date now, so DT now no longer tests on 3.6.

**Pull request merged**
